import fs from 'node:fs/promises';
import path from 'node:path';
import { Presentation, PresentationFile } from '@oai/artifact-tool';
const dir=path.resolve('presentation/.build');
const out=path.resolve('presentation/livraison');
const p=Presentation.create({slideSize:{width:1280,height:720}});
const C={paper:'#F8F6F0',ink:'#183E36',green:'#276653',muted:'#64766A',sage:'#E6EDE5'};
const notes=[];
function text(sl,txt,x,y,w,h,size=30,color=C.ink,bold=false){const a=sl.shapes.add({geometry:'textbox',name:txt.slice(0,45),position:{left:x,top:y,width:w,height:h},fill:'none',line:{fill:'none',width:0}});a.text=txt;a.text.style={typeface:'Arial',fontSize:size,color,bold,autoFit:'none',verticalAlignment:'middle'};return a;}
function slide(title,num,dark=false){const sl=p.slides.add();sl.background.fill=dark?C.ink:C.paper;if(title)text(sl,title,74,60,1132,120,48,dark?'#F8F6F0':C.ink);text(sl,String(num).padStart(2,'0'),1170,665,50,30,17,dark?'#B9CDBF':C.muted);return sl;}
function note(sl,title,time,script){sl.speakerNotes.textFrame.setText(time+'\n\n'+script+'\n\nSource : prototype Mythenena et modèle économique communiqué par l’équipe. Aucune donnée de traction ou de revenu mesurée.');notes.push({title,time,script});}
let s=slide('',1,true);
text(s,'MYTHENENA',74,90,1100,120,88,'#F8F6F0',true);
text(s,'Un espace pour parler\net prendre soin de soi',78,250,1050,150,48,'#F8F6F0');
text(s,'Maharavo, Tonintsoa, Irinah, Noel Pricio',80,585,1080,45,25,'#C8D8CC');
note(s,'Le pitch','00:00–00:45 · 45 secondes',`Imaginez une personne qui voudrait parler de ce qu’elle ressent, mais qui ne sait pas par où commencer. Mythenena lui propose un premier espace accessible depuis son téléphone : un échange avec une IA, des exercices pour prendre une pause, une communauté et un parcours vers un accompagnant humain. Nous sommes Maharavo, Tonintsoa, Irinah et Noel Pricio. Aujourd’hui, nous allons vous montrer notre prototype, le modèle économique que nous avons choisi et ce qu’il reste à construire. La démonstration est enregistrée dans cette présentation pour que vous puissiez suivre le parcours sans installation ni connexion au projet.`);
s=slide('Le premier pas peut être difficile',2);
text(s,'SCÉNARIO UTILISATEUR',78,215,900,40,19,C.muted);
text(s,'« J’ai besoin de parler.\nJe ne sais pas par où commencer. »',76,285,1120,160,46,C.ink);
text(s,'Aina, personnage fictif de notre démonstration',80,483,1090,45,24,C.muted);
text(s,'Notre point de départ : rendre ce premier geste plus simple.',80,583,1100,65,29,C.green);
note(s,'Le besoin','00:45–02:00 · 1 minute 15',`Notre point de départ est un besoin d’usage : pouvoir faire un premier geste lorsque l’on ressent du stress, une baisse de moral ou le besoin d’échanger. Aina est un personnage fictif. Nous ne présentons pas son histoire comme un témoignage utilisateur. Elle représente une situation que nous voulons explorer : elle ne souhaite pas forcément prendre un rendez-vous immédiatement. Elle veut d’abord trouver les mots, essayer un exercice ou lire ce que d’autres partagent. L’idée est de proposer plusieurs portes d’entrée, sans imposer le même parcours à tout le monde. À ce stade, nous ne prétendons pas avoir validé un marché ni démontré un effet clinique. Un pilote devra vérifier si cette proposition répond réellement aux attentes, quels parcours les personnes choisissent et à quel moment elles souhaitent un accompagnement humain.`);
s=slide('Un parcours accessible à son rythme',3);
text(s,'5 questions facultatives à l’arrivée',78,200,1100,70,36,C.green,true);
text(s,'Parler avec l’IA',78,320,480,50,31,C.ink,true);text(s,'Commencer un échange écrit ou vocal.',78,380,490,70,25,C.muted);
text(s,'Faire une pause',704,320,490,50,31,C.ink,true);text(s,'Choisir parmi cinq exercices guidés.',704,380,490,70,25,C.muted);
text(s,'Partager dans le forum',78,500,530,50,31,C.ink,true);text(s,'Échanger par thème, sous pseudonyme.',78,560,530,70,25,C.muted);
text(s,'Chercher un accompagnant',704,500,510,50,31,C.ink,true);text(s,'Consulter un profil et préparer un contact.',704,560,510,70,25,C.muted);
note(s,'La solution','02:00–03:00 · 1 minute',`Le parcours commence par cinq questions à choix multiples. Elles sont facultatives : une personne peut passer une question ou tout le questionnaire. Dans ce prototype, les réponses restent sur l’appareil et ne sont pas envoyées à l’IA. Ensuite, l’accueil donne accès aux espaces principaux. L’IA ouvre une conversation. Les ressources proposent cinq exercices. Le forum permet de partager sous pseudonyme. L’annuaire présente des accompagnants et permet d’enregistrer une demande de contact. L’interface propose le français, l’anglais et le malagasy. Nous allons maintenant suivre Aina. Les écrans que vous voyez sont ceux du prototype. Pour rendre le parcours reproductible et préserver les données, les échanges et les profils utilisés dans la vidéo sont des exemples fictifs.`);
const demos=[['Découvrir et parler','03:00–04:10 · 1 minute 10',`Aina arrive dans l’application. Elle peut répondre au questionnaire, mais elle garde la liberté de passer. Cette liberté évite de transformer l’entrée dans l’application en une longue formalité. Elle découvre ensuite l’accueil, puis rejoint l’assistant IA. Elle écrit une phrase simple sur son état du moment. La sphère accompagne visuellement les états de la conversation. La réponse montrée ici est un exemple préparé pour la démonstration, pas une réponse clinique validée. Le prototype dispose aussi d’un parcours vocal. Nous montrons ici l’écrit, afin que la démonstration ne dépende ni d’un microphone ni du son de l’ordinateur du jury. L’objectif est de permettre un premier échange, à son rythme.`],['Essayer les exercices','04:10–05:20 · 1 minute 10',`Aina choisit maintenant de faire une pause. Elle ouvre les ressources et lance une respiration guidée. La sphère se dilate et se relâche pour donner un rythme visuel doux. Elle peut choisir une durée, mettre en pause ou quitter l’exercice. Les autres ressources proposent un ancrage par les cinq sens, un moment de gratitude, un relâchement corporel et l’observation des pensées. Nous montrons ensuite le nuage qui se déplace : il matérialise le passage d’une pensée. Ces exercices ont leur place dans le quotidien, sans promettre une guérison. Dans notre offre prévue, le mode hors ligne donnera uniquement accès aux exercices. Le téléchargement et la disponibilité hors ligne complète restent à finaliser et à vérifier sur les appareils ciblés.`],['Retrouver le lien humain','05:20–06:30 · 1 minute 10',`Aina peut aussi rejoindre le forum. Les thèmes aident à retrouver une discussion, le pseudonyme permet de choisir la façon de se présenter, et les publications peuvent recevoir du soutien et des réponses. Le signalement est relié au service du forum. Elle consulte ensuite le profil d’un accompagnant, ses langues et ses spécialités, puis prépare une demande de contact. Le profil montré est fictif et aucun message réel n’est envoyé dans cette démonstration. Il faut distinguer cette demande de contact, qui existe dans le prototype, des appels directs aux psychologues, qui font partie de notre prochaine étape. La messagerie actuelle reste également une démonstration locale. Nous voulons construire le relais humain avec des professionnels, sans laisser croire que l’IA les remplace.`]];
for(let i=0;i<3;i++){s=slide('',4+i);let img=await fs.readFile(path.join(dir,`demo${i+1}-poster.png`));s.images.add({blob:img,contentType:'image/png',alt:`Démonstration ${i+1} du prototype dans un téléphone`,position:{left:0,top:0,width:1280,height:720}});note(s,demos[i][0],demos[i][1],demos[i][2]);}
s=slide('Trois offres, une même base accessible',7);
text(s,'IA illimitée, forum et exercices dans tous les plans',78,189,1120,70,30,C.green,true);
const values=[['Offre prévue','Gratuit','Premium','Premium Plus'],['Financement','Publicité en haut\nde page','Abonnement','Abonnement\nsupérieur'],['Psychologues','Non inclus','Crédits pour\nles appels directs','Accès total\net prioritaire']];
const table=s.tables.add({rows:3,columns:4,left:78,top:292,width:1124,height:236,columnWidths:[244,280,300,300],values});
for(let r=0;r<3;r++)for(let c=0;c<4;c++){const cell=table.getCell(r,c);cell.fill=r===0?C.green:r%2?C.sage:C.paper;cell.text.style={typeface:'Arial',fontSize:r===0?25:24,color:r===0?'#FFFFFF':C.ink,bold:r===0||c===0};}
text(s,'Hors ligne : exercices uniquement',78,562,1120,45,27,C.green,true);
text(s,'Tarifs, nombre de crédits et modalités de priorité à définir.',78,622,1090,35,20,C.muted);
note(s,'Le modèle économique','06:30–08:30 · 2 minutes',`Notre modèle repose sur des abonnements, avec une porte d’entrée gratuite. Tous les plans donnent accès à l’IA sans quota annoncé, au forum et aux exercices. Le gratuit comporte un panneau publicitaire en haut de page et ne donne pas accès aux psychologues. Le Premium apporte des crédits pour des appels directs avec des psychologues. Le Premium Plus donne accès à l’ensemble des services avec une priorité de prise en charge. Nous interprétons ici la priorité comme une priorité d’accès ou de réservation, dont les modalités devront être contractualisées avec les professionnels. Elle ne doit pas devenir une promesse de disponibilité immédiate. Les prix et le nombre de crédits ne sont pas encore fixés. Nous devons d’abord connaître le coût des minutes d’appel et la rémunération des psychologues. L’accès total ne signifie pas que nous avons déjà décidé d’offrir un nombre illimité d’heures de consultation. Ce point doit être précisé avant toute commercialisation. Hors ligne, seuls les exercices restent dans l’offre. L’IA, le forum et les appels demandent une connexion. Cette grille décrit le modèle cible, pas des abonnements déjà commercialisés.`);
s=slide('Financer un service qui reste accessible',8);
text(s,'Les revenus',78,218,500,60,35,C.green,true);
text(s,'Abonnements Premium et Premium Plus\nPublicité sur l’offre gratuite',78,302,515,150,29,C.ink);
text(s,'Les coûts à couvrir',704,218,500,60,35,C.green,true);
text(s,'Usage de l’IA\nTemps des psychologues\nModération et hébergement',704,302,500,190,29,C.ink);
text(s,'Le pilote doit mesurer le coût réel par utilisateur actif.',78,565,1120,65,31,C.green,true);
note(s,'La viabilité','08:30–10:00 · 1 minute 30',`Le point essentiel pour nous est de faire correspondre les revenus aux coûts du service. Les abonnements et la publicité doivent couvrir l’usage de l’IA, l’hébergement, la modération et surtout le temps des psychologues. Nous n’affichons pas de revenu prévisionnel ou de marge sans avoir ces données. Pendant un pilote, nous voulons mesurer le coût d’IA par utilisateur actif, le nombre de minutes d’appel consommées, le retour des personnes après une première utilisation et leur intérêt pour les offres payantes. L’IA illimitée est notre choix d’offre. Cela nous oblige à sélectionner une infrastructure adaptée, à suivre les coûts et à prévenir les usages automatisés abusifs. Les crédits servent à rendre le coût des échanges humains plus prévisible. Avant de fixer un tarif, nous devons également définir la durée couverte par un crédit et la rémunération du professionnel. Enfin, la publicité devrait rester distincte des conversations personnelles : nous proposons une publicité contextuelle, sans utiliser le contenu intime des échanges pour le ciblage. Ce principe reste à formaliser dans le lancement.`);
s=slide('Prochaine étape : un pilote encadré',9);
text(s,'Le prototype aujourd’hui',78,212,530,65,34,C.green,true);
text(s,'Questionnaire et accueil\nConversation IA et exercices\nForum et demandes de contact',78,300,540,170,28,C.ink);
text(s,'Les développements à venir',704,212,520,80,34,C.green,true);
text(s,'Appels et crédits psychologues\nPaiement, publicité et priorité\nMode hors ligne complet',704,315,500,165,28,C.ink);
text(s,'Nous cherchons des professionnels partenaires\net des premiers utilisateurs pour tester le parcours.',78,530,1100,90,32,C.green,true);
text(s,'Un outil de soutien au bien-être. Les soins relèvent des professionnels.',78,647,1100,30,20,C.muted);
note(s,'Le pilote et la conclusion','10:00–12:00 · 2 minutes',`Nous avons un prototype qui permet de montrer le parcours et de tester plusieurs interactions. Il reste du travail avant un service commercial : les appels avec crédits, les abonnements, la publicité, les règles de priorité et la disponibilité hors ligne complète. Nous devons également organiser la modération humaine, préciser la conservation des données et tester les situations sensibles de l’assistant. Mythenena est un outil de soutien au bien-être. Nous ne présentons pas l’IA comme un psychologue, un outil de diagnostic ou un service d’urgence. Le relais vers les professionnels est une partie essentielle du projet. La prochaine étape que nous proposons est un pilote avec des accompagnants partenaires et un petit groupe d’utilisateurs volontaires. Nous voulons observer où les personnes comprennent le parcours, où elles hésitent et ce qui leur donne envie de revenir. Ensuite, ces retours et les coûts réels permettront de fixer les tarifs et les crédits. Ce que nous recherchons auprès du jury, c’est un retour sur la pertinence du parcours, des mises en relation avec des professionnels et un cadre pour mener ce pilote. Notre ambition est de rendre le premier pas plus accessible et de créer un chemin clair vers l’aide humaine.`);
s=slide('',10,true);text(s,'Vos questions',78,145,1100,120,80,'#F8F6F0',true);text(s,'3 minutes d’échange',80,312,1100,60,35,'#C8D8CC');text(s,'MYTHENENA',80,496,1100,60,35,'#F8F6F0',true);text(s,'Maharavo, Tonintsoa, Irinah, Noel Pricio',80,583,1100,50,26,'#C8D8CC');
note(s,'Questions et réponses','12:00–15:00 · 3 minutes',`Réponses courtes, puis approfondir si le jury le demande. Prix : ils restent à définir après mesure des coûts et échanges avec les professionnels. Crédits : leur valeur en minutes et leur renouvellement restent à fixer. IA illimitée : engagement d’offre, avec suivi des coûts et prévention des abus, sans vendre un quota caché. Premium Plus : accès total et prioritaire, modalités précises à définir, sans promesse d’heures de consultation illimitées à ce stade. Hors ligne : exercices uniquement dans l’offre prévue, fonctionnement complet encore à finaliser. Confidentialité : les réponses au questionnaire restent sur l’appareil dans le prototype, les autres traitements demandent une politique de conservation et de protection formalisée. Démo : vrais écrans du prototype, profils et échanges fictifs, vidéos embarquées. Validation : pas encore de preuve clinique, de traction ou de revenus annoncés. Publicité : bandeau sur le gratuit, ciblage intime non prévu dans la proposition. Différenciation : un parcours qui relie échange IA, exercices, communauté et accompagnants, avec une interface multilingue.`);
await (await PresentationFile.exportPptx(p)).save(path.join(dir,'candidate.pptx'));
for(let i=0;i<p.slides.items.length;i++){const blob=await p.export({slide:p.slides.items[i],format:'png',scale:1});await fs.writeFile(path.join(dir,`slide-${i+1}.png`),new Uint8Array(await blob.arrayBuffer()));}
await fs.writeFile(path.join(dir,'notes.json'),JSON.stringify(notes,null,2));
await fs.writeFile(path.join(out,'Guide_oral_15_minutes.md'),'# Mythenena — guide de soutenance\n\n12 minutes de présentation et 3 minutes de questions. Les vidéos sont silencieuses pour laisser la parole au présentateur.\n\n'+notes.map((n,i)=>`## ${i+1}. ${n.title}\n\n${n.time}\n\n${n.script}`).join('\n\n')+'\n\n## Sur l’ordinateur du jury\n\nCopier le dossier complet sur le disque local. Ouvrir le PowerPoint en mode Diaporama. Les vidéos des diapositives 4 à 6 doivent démarrer automatiquement. Si elles ne démarrent pas, cliquer sur la vidéo. Les fichiers MP4 séparés servent de secours, et le PDF permet une présentation statique. Aucune connexion au projet n’est nécessaire. Faire un essai sur l’ordinateur avant le passage.\n');
console.log('Draft and previews created');
