import type { Language } from './i18n';

const fr = {
  eyebrow: 'Votre espace ressources', title: 'Un peu de calme.\nÀ votre rythme.', intro: 'Choisissez ce qui vous ferait du bien, ici et maintenant.',
  first: 'Pour commencer', breath: 'Retrouver son souffle.', breathNote: 'Une sphère, un souffle.\nRien d’autre à faire.', tryBreath: 'Essayer la respiration', others: 'Exercices',
  titles: ['Revenir à l’instant', 'Les petites choses', 'Relâcher les tensions', 'Laisser passer les pensées'],
  descriptions: ['Les 5 sens · à votre rythme', 'Gratitude · 3 invitations', 'Le corps · 4 étapes douces', 'Un ciel, des nuages · à votre rythme'],
  noStreak: 'Pas de série à maintenir.\nJuste un moment qui vous appartient.', back: 'Ressources', start: 'Commencer', pause: 'Mettre en pause', resume: 'Reprendre', finish: 'Terminer ce moment', stop: 'Terminer maintenant', next: 'Continuer', skip: 'Passer cette étape', of: 'sur', step: 'Étape',
  thanks: 'Merci d’avoir\npris ce temps.', doneNote: 'Vous pouvez reprendre votre journée, tout simplement.', return: 'Retour aux ressources', moment: 'Un moment pour vous',
  breathIntro: 'Suivez le mouvement, sans forcer. Vous pouvez garder votre propre rythme.', sit: 'Installez-vous.', inhale: 'Inspirez…', exhale: 'Expirez…', paused: 'En pause.', noHold: 'Sans rétention', breathCue: 'Inspirez puis expirez doucement, sans retenir l’air.', breathFoot: 'Si le rythme ne vous convient pas, respirez naturellement ou arrêtez l’exercice.',
  senses: ['Regardez autour de vous', 'Sentez les textures', 'Écoutez les alentours', 'Remarquez les odeurs', 'Portez attention au goût'],
  senseNotes: ['5 choses que vous voyez.', '4 choses que vous pouvez toucher.', '3 sons que vous entendez.', '2 odeurs que vous percevez.', '1 goût que vous percevez.'],
  stone: 'Élément remarqué', touch: 'Touchez un galet pour chaque élément.', nextSense: 'Passer au sens suivant', sensesFoot: 'Prenez votre temps. Vous pouvez passer un sens qui ne vous est pas accessible.',
  gratitudeTitle: 'Cultiver\nun peu de douceur.', invitation: 'Invitation', optional: 'Sans obligation d’écrire',
  prompts: ['Un petit moment agréable aujourd’hui…', 'Une personne, un lieu ou une chose qui compte…', 'Une petite chose que vous avez faite pour vous…'],
  placeholder: 'Même une chose toute simple…', journalLabel: 'Votre petit moment', plant: 'Faire grandir ma plante', skipPrompt: 'Passer cette invitation', keep: 'Gardez ces petites choses avec vous.', journalDone: 'Votre moment est terminé', journalFoot: 'Vous pouvez aussi simplement y penser. Vos mots ne sont ni envoyés ni enregistrés ; ils disparaissent en quittant cet exercice.',
  bodyIntro: 'Installez-vous confortablement. Il n’y a rien à réussir.', bodyParts: ['Le visage', 'Les épaules', 'Les mains', 'Les pieds'],
  bodyNotes: ['Remarquez les sensations du visage. Si cela vous est agréable, laissez la mâchoire se desserrer.', 'Remarquez vos épaules. Vous pouvez les laisser retomber naturellement, sans les forcer.', 'Portez votre attention sur vos mains. Laissez vos doigts reposer comme ils le souhaitent.', 'Remarquez le contact des pieds avec le sol, ou du corps avec son support.'],
  bodyFoot: 'Vous pouvez passer une étape en continuant. Gardez seulement ce qui vous est confortable.',
  thoughtIntro: 'Une pensée peut être là, sans demander une réponse tout de suite.', thought: 'Une pensée…', observe: 'Observez simplement.', thoughtNote: 'Imaginez une pensée sur ce nuage. Regardez-la passer, sans chercher à la chasser.', drift: 'Regarder le nuage passer', drifting: 'Laissez le nuage avancer…', driftNote: 'Pas besoin de le pousser. Prenez le temps de regarder son mouvement.', space: 'Un peu d’espace.', again: 'Observer une autre pensée', thoughtFoot: 'Si la pensée revient, c’est normal. Vous pouvez revenir à ce que vous voyez autour de vous.',
};
const en: typeof fr = {
  eyebrow: 'Your resource space', title: 'A little calm.\nAt your own pace.', intro: 'Choose what feels right for you, here and now.', first: 'Start here', breath: 'Find your breath.', breathNote: 'A sphere, a breath.\nNothing else to do.', tryBreath: 'Try breathing', others: 'Exercises',
  titles: ['Return to the present', 'The little things', 'Release tension', 'Let thoughts pass'], descriptions: ['The 5 senses · at your pace', 'Gratitude · 3 invitations', 'The body · 4 gentle steps', 'A sky, some clouds · at your pace'], noStreak: 'No streak to keep.\nJust a moment for you.', back: 'Resources', start: 'Start', pause: 'Pause', resume: 'Resume', finish: 'Finish this moment', stop: 'Finish now', next: 'Continue', skip: 'Skip this step', of: 'of', step: 'Step', thanks: 'Thank you for\ntaking this time.', doneNote: 'Simply return to your day.', return: 'Back to resources', moment: 'A moment for you',
  breathIntro: 'Follow the movement without forcing. You can keep your own rhythm.', sit: 'Settle in.', inhale: 'Breathe in…', exhale: 'Breathe out…', paused: 'Paused.', noHold: 'No breath holding', breathCue: 'Breathe in and out gently, without holding your breath.', breathFoot: 'If this pace does not suit you, breathe naturally or stop the exercise.',
  senses: ['Look around you', 'Notice textures', 'Listen around you', 'Notice smells', 'Notice taste'], senseNotes: ['5 things you can see.', '4 things you can touch.', '3 sounds you can hear.', '2 smells you can notice.', '1 taste you can notice.'], stone: 'Noticed item', touch: 'Tap a pebble for each item.', nextSense: 'Go to the next sense', sensesFoot: 'Take your time. You can skip a sense that is not accessible to you.',
  gratitudeTitle: 'Grow a little\ngentleness.', invitation: 'Invitation', optional: 'Writing is optional', prompts: ['A small pleasant moment today…', 'A person, place or thing that matters…', 'One little thing you did for yourself…'], placeholder: 'Even something very simple…', journalLabel: 'Your little moment', plant: 'Grow my plant', skipPrompt: 'Skip this invitation', keep: 'Keep these little things with you.', journalDone: 'Your moment is complete', journalFoot: 'You can also just think about it. Your words are not sent or saved; they disappear when you leave this exercise.',
  bodyIntro: 'Make yourself comfortable. There is nothing to achieve.', bodyParts: ['Face', 'Shoulders', 'Hands', 'Feet'], bodyNotes: ['Notice sensations in your face. If comfortable, allow your jaw to soften.', 'Notice your shoulders. You can let them drop naturally without forcing them.', 'Bring attention to your hands. Let your fingers rest comfortably.', 'Notice your feet against the floor, or your body against its support.'], bodyFoot: 'You can skip a step by continuing. Keep only what feels comfortable.',
  thoughtIntro: 'A thought can be here without needing an answer right away.', thought: 'A thought…', observe: 'Simply observe.', thoughtNote: 'Imagine a thought on this cloud. Watch it pass without trying to push it away.', drift: 'Watch the cloud pass', drifting: 'Let the cloud move…', driftNote: 'No need to push it. Take time to watch its movement.', space: 'A little space.', again: 'Observe another thought', thoughtFoot: 'It is normal if the thought returns. You can come back to what you see around you.',
};
const mg: typeof fr = {
  eyebrow: 'Ny loharano ho anao', title: 'Fitoniana kely.\nAraka izay mety aminao.', intro: 'Fidio izay mety aminao eto sy amin’izao fotoana izao.', first: 'Hanombohana', breath: 'Haka aina.', breathNote: 'Boribory iray, fofonaina iray.\nTsy misy zavatra hafa atao.', tryBreath: 'Hanandrana ny fofonaina', others: 'Fanazaran-tena',
  titles: ['Hiverina amin’ny ankehitriny', 'Ny zavatra madinika', 'Hampitony ny vatana', 'Hamela ny eritreritra handalo'], descriptions: ['Ny retsi-pandre 5 · araka izay mety aminao', 'Fankasitrahana · fanasana 3', 'Ny vatana · dingana malefaka 4', 'Lanitra sy rahona · araka izay mety aminao'], noStreak: 'Tsy misy isa tsy maintsy tratrarina.\nFotoana ho anao fotsiny.', back: 'Loharano', start: 'Hanomboka', pause: 'Hiato', resume: 'Hanohy', finish: 'Hamita izao fotoana izao', stop: 'Hamita izao', next: 'Hanohy', skip: 'Handalo ity dingana ity', of: 'amin’ny', step: 'Dingana', thanks: 'Misaotra anao\nnaka fotoana.', doneNote: 'Afaka manohy ny andronao ianao.', return: 'Hiverina amin’ny loharano', moment: 'Fotoana ho anao',
  breathIntro: 'Araho moramora ny fihetsika, tsy terena. Afaka manaraka ny gadonao ianao.', sit: 'Mipetraha tsara.', inhale: 'Mifoka rivotra…', exhale: 'Mamoaka rivotra…', paused: 'Miato.', noHold: 'Tsy mitana fofonaina', breathCue: 'Mifoka sy mamoaka rivotra moramora, tsy mitana fofonaina.', breathFoot: 'Raha tsy mety aminao ny gadona dia miaina ara-dalàna na ajanony ny fanazaran-tena.',
  senses: ['Jereo ny manodidina', 'Tsapao ny zavatra', 'Henoy ny manodidina', 'Fantaro ny fofona', 'Fantaro ny tsiro'], senseNotes: ['Zavatra 5 hitanao.', 'Zavatra 4 azonao tsapaina.', 'Feo 3 henonao.', 'Fofona 2 tsapanao.', 'Tsiro 1 tsapanao.'], stone: 'Zavatra voamarika', touch: 'Tsindrio ny vato iray isaky ny zavatra.', nextSense: 'Ho amin’ny retsi-pandre manaraka', sensesFoot: 'Makà fotoana. Afaka mandalo retsi-pandre tsy azonao ampiasaina ianao.',
  gratitudeTitle: 'Hamboly\nhalemem-panahy.', invitation: 'Fanasana', optional: 'Tsy voatery hanoratra', prompts: ['Fotoana kely nahafinaritra androany…', 'Olona, toerana na zavatra sarobidy…', 'Zavatra kely nataonao ho an’ny tenanao…'], placeholder: 'Na zavatra tsotra aza…', journalLabel: 'Ny fotoananao', plant: 'Hampitombo ny zavamaniry', skipPrompt: 'Handalo ity fanasana ity', keep: 'Tehirizo ao am-ponao ireo zavatra madinika ireo.', journalDone: 'Vita ny fotoananao', journalFoot: 'Azonao eritreretina fotsiny izany. Tsy alefa na tahirizina ny soratrao; voafafa rehefa miala amin’ity fanazaran-tena ity ianao.',
  bodyIntro: 'Mipetraha tsara. Tsy misy tanjona tsy maintsy tratrarina.', bodyParts: ['Ny tarehy', 'Ny soroka', 'Ny tanana', 'Ny tongotra'], bodyNotes: ['Tsapao ny tarehinao. Raha mahazo aina ianao dia avelao hiala sasatra ny valanoranonao.', 'Tsapao ny sorokao. Avelao hilamina tsy terena.', 'Mifantoha amin’ny tananao. Avelao hiala sasatra ny rantsantananao.', 'Tsapao ny tongotrao amin’ny tany na ny vatanao amin’ny tohana.'], bodyFoot: 'Afaka mandalo dingana ianao amin’ny fanohizana. Ataovy izay mampahazo aina anao ihany.',
  thoughtIntro: 'Mety hisy eritreritra tsy mila valiny avy hatrany.', thought: 'Eritreritra iray…', observe: 'Diniho fotsiny.', thoughtNote: 'Alaivo sary an-tsaina eo amin’ity rahona ity ny eritreritra. Jereo handalo fa aza terena hiala.', drift: 'Hijery ny rahona handalo', drifting: 'Avelao handroso ny rahona…', driftNote: 'Tsy mila atosika. Makà fotoana hijerena azy.', space: 'Elanelana kely.', again: 'Hijery eritreritra hafa', thoughtFoot: 'Ara-dalàna raha miverina ny eritreritra. Afaka miverina mijery ny manodidina anao ianao.',
};
export type ResourcesCopy = typeof fr;
export const resourcesCopy: Record<Language, ResourcesCopy> = { fr, en, mg };
